apiVersion: v1
data:
  PAAS_FRONTNED_REPLICAS: 0
kind: ConfigMap
metadata:
  name: paas-stack-config
  namespace: devops
---
apiVersion: v1
data:
  CONSUL_ENDPOINT: https://consul.non-prod.plivops.com
  KEYCLOAK_DNS: keycloak.non-prod.plivops.com
  KEYCLOAK_IMAGE: 857556598075.dkr.ecr.us-west-1.amazonaws.com/plivo/paas-stack-keycloak:24.07.19.1444
  OAUTH2PROXY_IMAGE: 857556598075.dkr.ecr.us-west-1.amazonaws.com/plivo/paas-stack-oauth2proxy:paas-stack-keycloak-24.07.15.7
  PAAS_DNS: paas.non-prod.plivops.com
  PAAS_FRONTNED_REPLICAS: 0
kind: ConfigMap
metadata:
  name: paas-stack-config
  namespace: devops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paas-stack-keycloak
  namespace: devops
spec:
  interval: 5m0s
  path: ./paas-stack/keycloak
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: paas-stack-config
  prune: true
  replicas: 0
  sourceRef:
    kind: GitRepository
    name: platform-manifests
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paas-stack-o2p
  namespace: devops
spec:
  interval: 5m0s
  path: ./paas-stack/oauth2proxy
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: paas-stack-config
  prune: true
  replicas: 0
  sourceRef:
    kind: GitRepository
    name: platform-manifests
    namespace: flux-system
---
apiVersion: v1
data:
  PAAS_FRONTNED_REPLICAS: 0
kind: ConfigMap
metadata:
  name: paas-stack-config
  namespace: devops
