apiVersion: v1
data:
  PAAS_FRONTNED_REPLICAS: 0
kind: ConfigMap
metadata:
  name: paas-stack-config
  namespace: devops
spec:
  advanced:
    exposePodInfo: true
  consul: https://consul.non-prod.plivops.com
  containerPort: 3000
  image: 857556598075.dkr.ecr.us-west-1.amazonaws.com/plivo/devops/paas:dev-d5984ad-1722497106221
  loadbalancing:
    listenerPorts:
      - 443
    public: false
    targetGroup:
      healthcheck:
        path: /
    useCommonLoadbalancer: true
  replicas: 0
  resources:
    limits:
      cpu: '2'
      memory: 3Gi
    requests:
      cpu: '1.5'
      memory: 2Gi
  securityContext:
    allowPrivilegeEscalation: true
    fsGroup: 0
    privileged: true
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
